In [ ]:
import numpy as np
import pandas as pd

import nltk
import re
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer


nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [ ]:
tweets = pd.read_csv(r'/content/drive/MyDrive/Minor Project/Minor Project/influenza_tweets.csv')
tweets.head()

,Date,Text
0,2025-02-21 06:19:21+00:00,RT @ColonelRETJohn2: Stacey needs to cough up ...
1,2025-02-21 06:19:16+00:00,"@xai @elonmusk @elonmusk, Grok 3 coded rage be..."
2,2025-02-21 06:19:15+00:00,@HashMonie @TheJoeySwoll Cough cough **douch**...
3,2025-02-21 06:19:14+00:00,RT @lenaalovessyouu: that pen cough sum different
4,2025-02-21 06:18:56+00:00,well *cough cough* nigga! https://t.co/Ziiaq7tsT0

In [ ]:
def clean_tweet(tweet):

    tokens = nltk.word_tokenize(tweet)

    tokens = [token.lower() for token in tokens]

    stop_words = set(nltk.corpus.stopwords.words('english'))
    tokens = [token for token in tokens if token.isalnum() and token not in stop_words]

    cleaned_tweet = ' '.join(tokens)

    return cleaned_tweet

In [ ]:
cleaned_tweets = tweets['Text'].apply(clean_tweet)

In [ ]:
cleaned_tweets.head()

0    rt colonelretjohn2 stacey needs cough every do...
1    xai elonmusk elonmusk grok 3 coded rage bears ...
2       hashmonie thejoeyswoll cough cough douch cough
3           rt lenaalovessyouu pen cough sum different
4                         well cough cough nigga https
Name: Text, dtype: object

In [ ]:
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

def stem_tweet(tweet):
    tokens = nltk.word_tokenize(tweet)
    stemmed_tokens = [stemmer.stem(token) for token in tokens]
    return ' '.join(stemmed_tokens)

def lemmatize_tweet(tweet):
    tokens = nltk.word_tokenize(tweet)
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    return ' '.join(lemmatized_tokens)

stemmed_tweets = cleaned_tweets.apply(stem_tweet)
lemmatized_tweets = cleaned_tweets.apply(lemmatize_tweet)

print("Stemmed Tweets:")
print(stemmed_tweets.head())

print("\nLemmatized Tweets:")
print(lemmatized_tweets.head())

Stemmed Tweets:
0    rt colonelretjohn2 stacey need cough everi dol...
1    xai elonmusk elonmusk grok 3 code rage bear 10...
2         hashmoni thejoeyswol cough cough douch cough
3              rt lenaalovessyouu pen cough sum differ
4                          well cough cough nigga http
Name: Text, dtype: object

Lemmatized Tweets:
0    rt colonelretjohn2 stacey need cough every dol...
1    xai elonmusk elonmusk grok 3 coded rage bear 1...
2       hashmonie thejoeyswoll cough cough douch cough
3           rt lenaalovessyouu pen cough sum different
4                          well cough cough nigga http
Name: Text, dtype: object

In [ ]:
from nltk import pos_tag
def pos_tag_tweet(tweet):
  tokens = nltk.word_tokenize(tweet)
  return pos_tag(tokens)

pos_tagged_tweets = cleaned_tweets.apply(pos_tag_tweet)
print("\nPOS Tagged Tweets:")
print(pos_tagged_tweets.head())

POS Tagged Tweets:
0    [(rt, NN), (colonelretjohn2, NN), (stacey, NN)...
1    [(xai, JJ), (elonmusk, NN), (elonmusk, NN), (g...
2    [(hashmonie, NN), (thejoeyswoll, NN), (cough, ...
3    [(rt, NN), (lenaalovessyouu, NN), (pen, JJ), (...
4    [(well, RB), (cough, JJ), (cough, NN), (nigga,...
Name: Text, dtype: object

In [ ]:
from nltk.sentiment import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

sia = SentimentIntensityAnalyzer()

tweets['cleaned_tweets'] = cleaned_tweets

tweets['sentiment'] = tweets['cleaned_tweets'].apply(lambda tweet: sia.polarity_scores(tweet)['compound'])

tweets['sentiment_label'] = tweets['sentiment'].apply(lambda score: 'positive' if score >= 0 else 'negative')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [ ]:
tweets.head()

,Date,Text,cleaned_tweets,sentiment,sentiment_label
0,2025-02-21 06:19:21+00:00,RT @ColonelRETJohn2: Stacey needs to cough up ...,rt colonelretjohn2 stacey needs cough every do...,-0.2960,negative
1,2025-02-21 06:19:16+00:00,"@xai @elonmusk @elonmusk, Grok 3 coded rage be...",xai elonmusk elonmusk grok 3 coded rage bears ...,-0.7964,negative
2,2025-02-21 06:19:15+00:00,@HashMonie @TheJoeySwoll Cough cough **douch**...,hashmonie thejoeyswoll cough cough douch cough,0.0000,positive
3,2025-02-21 06:19:14+00:00,RT @lenaalovessyouu: that pen cough sum different,rt lenaalovessyouu pen cough sum different,0.0000,positive
4,2025-02-21 06:18:56+00:00,well *cough cough* nigga! https://t.co/Ziiaq7tsT0,well cough cough nigga https,0.2732,positive